<div id="opDialogLogin" class="op-hide" title="Форма авторизации">
    <div>
        Регистрироваться не обязательно, просто введи желаемый логин или 
        логин и пароль и система авторизирует тебя под ним.
    </div>
    
    <form method="post">
        <table class="op-table op-w100">
            <tr>
                <th>
                    Логин *
                </th>
                <td>
                    <input type="text" name="login" value="" class="op-w100"/>
                </td>
            </tr>
            <tr>
                <th>
                    Пароль
                </th>
                <td>
                    <input type="password" name="password" value="" class="op-w100"/>
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Авторизация" />
                </td>
            </tr>
        </table>
    </form>
</div>