<div id="opDialogLogin" class="op-hide" title="<?php echo __('Auth form') ?>">
    <div>
        <?php echo __('Registration is optional, just input login or login and password and system authorise you with it') ?>.
    </div>
    
    <form method="post">
        <table class="op-table op-w100">
            <tr>
                <th>
                    <?php echo __('Login') ?>*
                </th>
                <td>
                    <input type="text" name="login" value="" class="op-w100"/>
                </td>
            </tr>
            <tr>
                <th>
                    <?php echo __('Password') ?>
                </th>
                <td>
                    <input type="password" name="password" value="" class="op-w100"/>
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="<?php echo __('Authorise') ?>" />
                </td>
            </tr>
        </table>
    </form>
</div>