<div class="op-song" 
     data-id="<?= $song['id'] ?>" 
     data-plid="<?= $plId ?>" 
     data-url="<?= $song['url'] ?>" 
     data-name="<?= $song['name'] ?>" 
     data-artist="<?= $song['artist'] ?>" 
     data-duration="<?= $song['duration'] ?>"
     data-position="<?= isset($position) ? $position : null ?>">

    <div class="op-subsong">
        <div class="op-fl">
            <a href="javascript:" class="op-icons op-icon-song-play op-link-song-play">&nbsp;</a>
        </div>

        <div>
            <a href="javascript:void(0)" class="op-atrist"><?= $song['artist'] ?></a> 
             - 
            <?= $song['name'] ?> 
            (<?= $song['duration'] ?>)

            <span class="op-fr">
                <?php
                $normalUrl = Lib\Config::getInstance()->getOption('app', 'baseUrl') . "?l=1&q=".urlencode(trim($song['artist']).'-'.trim($song['name']));
                $url = urlencode($normalUrl);
                $text = urlencode("{$song['artist']}-{$song['name']} #openwebplayer #nowplaying");
                $via= "openwebplayer";
                ?>

                <a title="Ссылка на трек" class="op-icons op-icon-link" href="javascript:" onclick="prompt('Ссылка на трек', '<?=$normalUrl?>')">&nbsp;</a>
                |
                <a title="Твитнуть" class="op-icons op-icon-twitter" target="_blank" href="http://twitter.com/share?via=<?php echo $via?>&url=<?=$url?>&text=<?php echo $text?>">&nbsp;</a>
                <a title="Показать друзьям вконтакте" class="op-icons op-icon-vk" target="_blank" href="http://vkontakte.ru/share.php?title=<?php echo $text?>&description=<?php echo $text?> <?php echo $url?>">&nbsp;</a>
                <a title="Показать друзьям в фейсбуке" class="op-icons op-icon-facebook" target="_blank" href="http://www.facebook.com/sharer.php?u=<?php echo $url?>&t=<?php echo $text?> <?php echo $url?>">&nbsp;</a>

                
                    <span class="op-song-del-span <? if (!$plId): ?>op-hide<? endif ?>">
                        |
                        <a href="javascript:" 
                           class="op-link-song-del op-icons op-icon-song-del" 
                           data-id="<?= $song['id'] ?>"
                           data-plid="<?= $plId ?>">&nbsp;</a>
                    </span>
                
                
            </span>

        </div>
    </div>
</div>