<!DOCTYPE html>
<html>
    <head>
        <title><?php echo \Lib\Config::getInstance()->getOption('app', 'title') ?></title>
        
        <base href="<?php echo \Lib\Config::getInstance()->getOption('app', 'baseUrl') ?>"/>
        
        <meta charset="<?php echo \Lib\Config::getInstance()->getOption('app', 'charset') ?>"/>
        
        <script type="text/javascript" src="./web/js/jquery.js"></script>
        <script type="text/javascript" src="./web/js/jquery-ui.js"></script>
        <script type="text/javascript" src="./web/lib/jquery.jplayer.min.js"></script>
        
        <script type="text/javascript" src="./web/js/Loading.js"></script>
        <script type="text/javascript" src="./web/js/Playlists.js"></script>
        
        <link href="./web/css/index.css" rel="stylesheet" media="all" />
        <link href="./web/css/design.css" rel="stylesheet" media="all" />
        <link href="./web/css/jquery-ui.custom.css" rel="stylesheet" media="all" />
        
        <link rel="icon" type="image/png" href="./web/img/icon.png" />
    </head>
    
    <body class="op">
        <script type="text/javascript">
            if ( location.hash.match(/#!/) ) {
                location.href = location.hash.replace("#!", "");
            }
            
            var Settings = <?php echo json_encode(\Lib\Config::getInstance()->getOptions('client'))?>;
        </script>
        
        <?php echo $this->content ?>
        
        
        <?php if (\Lib\Config::getInstance()->getOption('app', 'GoogleAnalytics')): ?>
            <script type="text/javascript">
                  var _gaq = _gaq || [];
                  _gaq.push(['_setAccount', '<?php echo \Lib\Config::getInstance()->getOption('app', 'GoogleAnalytics') ?>']);
                  _gaq.push(['_trackPageview']);

                  (function() {
                    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
                  })();

            </script>
        <?php endif ?>
        
    </body>
</html>