<strong><?php echo __('Basic player features') ?></strong>
<ul>
    <li>
        <strong><?php echo __('Search') ?>.</strong> <?php echo __('Search using vkontakte music database.') ?>
    </li>
    <li>
        <strong><?php echo __('Simple authorisation') ?>.</strong> <?php echo __('Authorisation is optional, and needed only to access your playlists. Login and Registration not separated, so you can login by <b>any</b> login or login and password you want. Password is also optional.') ?>
    </li>
    <li>
        <strong><?php echo __('Playlists') ?>.</strong> <?php echo __('Playlists available only for authorised users. It needs to group your music.') ?>
    </li>
    <li>
        <strong><?php echo __('Drag & Drop') ?>.</strong> <?php echo __('Useful controll player using Drag&Drop.') ?>
    </li>
    <li>
        <strong><?php echo __('Social integration') ?>.</strong> <?php echo __('Share music with friends in vkontakte, facebook & twitter.') ?>
    </li>
    <li>
        <strong><?php echo __('Link on track') ?>.</strong> <?php echo __('Also you can share direct link to music with your friend in jabber, skype, icq or in any other way.') ?>
    </li>
    <li>
        <strong><?php echo __('Recommendations') ?>.</strong> <?php echo __('Recommendations is based on listened music database.') ?> 
    </li>
    <li>
        <strong><?php echo __('Saerch history') ?>.</strong> <?php echo __('Your search history.') ?> 
    </li>
</ul>

<strong><?php echo __('And what are the advantages?') ?></strong>
<ul>
    <li>
        <strong><?php echo __('Decentralisation') ?>.</strong> <?php echo __('Open Player everybody can setup on his own LAMP-hosting.') ?> 
    </li>
    <li>
        <strong><?php echo __('Free and opensource') ?>.</strong> <?php echo __('This project is opensource, and spread "as is", so everybody can modify it.') ?>
    </li>
</ul>

<strong><?php echo __('Supported browsers') ?></strong>
<ul>
    <li>
        <?php echo __('Unfortunately this version can work incorrect in some browsers. It must good work in Firefox 4+ and Google Chrome.') ?>
    </li>
</ul>
    
<strong><?php echo __('How to setup it on your own hosting?') ?></strong>
<ul>
    <li>
        <?php echo __('Install instructions is located on') ?>
        <a class="op-underline" target="_blank" href="http://bonart.org.ua/page/openplayer"><?php echo __('project page') ?></a>.
    </li>
</ul>

<strong><?php echo __('Have questions?') ?></strong>
<ul>
    <li>
        <a target="_blank" title="<?php echo __('Project news in twitter') ?>" class="op-underline" href="http://twitter.com/openwebplayer"><?php echo __('Project news in twitter') ?></a>
    </li>
    <li>
        <a target="_blank" title="<?php echo __('Discussion on google plus') ?>" class="op-underline" href="https://plus.google.com/u/1/100300191451326989757/posts/UDvzX4jkDbG"><?php echo __('Discussion on google plus') ?></a>
    </li>
    <li>
        <a target="_blank" title="<?php echo __('Vkontakte project group') ?>" class="op-underline" href="http://vk.com/openwebplayer"><?php echo __('Vkontakte project group') ?></a>
    </li>
    <li>
        <a target="_blank" title="<?php echo __('Facebook project group') ?>" class="op-underline" href="http://facebook.com/groups/145224552223981"><?php echo __('Facebook project group') ?></a>
    </li>
</ul>

<!-- v0.12 -->
