<div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div class="jp-audio">
	<div class="jp-type-single">
		<div id="jp_interface_1" class="jp-interface">
			<div class="jp-pause"></div>
			<div class="jp-play"></div>
			<div class="jp-progress">
				<span id="song-title"></span>
				<div class="jp-seek-bar">
					<div class="jp-play-bar"></div>
				</div>
			</div>
			<div class="jp-right">
				<div class="jp-shuffle" title="Случайный [ВЫКЛ]"></div>
				<div class="jp-repeat" title="Повтор [ВЫКЛ]"></div>
				<div class="jp-mute"></div>
				<div class="jp-unmute"></div>
				<div class="jp-volume-bar">
					<div class="jp-volume-bar-value"></div>
				</div>
			</div>
		</div>
	</div>
</div>