<?php $q = \Lib\Request::get('q') ?>
<?php $offset = \Lib\Request::get('offset') ?>
<?php $songsCount = \Lib\Config::getInstance()->getOption('app', 'songsCount') ?>

<?php if ( !\Lib\Request::get('short') ): ?> 
    <div class="op-container-songbox op-container-songs" id="opContainerSongs">
        <?php require ROOT . '/views/templates/_songs.phtml' ?>
    </div>

    <?php if ( !\Lib\Request::get('l') ): ?> 
        <?php if ( $offset ): ?> 
            <a id="opPagerSongsPrev" href="?q=<?php echo urlencode($q)?>&offset=<?php echo ($offset - $songsCount) ?>">&laquo; <?php echo __('Previous') ?></a>
        <?php endif ?>
        
        <?php if ( count($this->songs) >= $songsCount ): ?>
            <a id="opPagerSongsNext" href="?q=<?php echo urlencode($q) ?>&offset=<?php echo ($offset + $songsCount) ?>"><?php echo __('Next') ?> &raquo;</a>
        <?php endif ?>
    <?php endif ?>
<?php else: ?>
    <?php require ROOT . '/views/templates/_songs.phtml' ?>
<?php endif ?>